from pydantic import BaseModel
from typing import List
class SummarizeRequest(BaseModel):
    text: str
class Message(BaseModel):
    role: str
    content: str
    chatRound: int
    imageNumber: int
class Messages(BaseModel):
    messages: List[Message]
class Emotions(BaseModel):
    joy: float
    sadness: float
    anger: float
    fear: float
class CompleteRequest(BaseModel):
    user_id: str
    messages: List[Message]
    timestamp: str
    gender: str
class ReviewRequest(BaseModel):
    user_id: str
class SuggestionContent(BaseModel):
    anxiety: str
    advice: str
class SuggestionType(BaseModel):
    fortune_telling: str
    religion: str
    quote: str
    philosophy: str
class TenBullsAdviceAndLevel(BaseModel):
    advice: str
    level: int
class TenBullsDataRequest(BaseModel):
    user_id: str
class TenBullsData(BaseModel):
    advice: str
    level: int
    user_id: str

class FeedbackRequest(BaseModel):
    user_id: str
    scores: List[int]